# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:

np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Lib

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
a=np.array([1,2,3,4])
b=a.nbytes
print(b)

16


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
a=np.arange(1,5)
b=a[::-1]
print(b)

[4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
a=np.arange(9)
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
a=[1,2,0,0,4,0]
b=np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
a=np.random.rand(3,3,3)
print(a)

[[[0.64166708 0.73366071 0.12491274]
  [0.86192452 0.71995319 0.93954751]
  [0.31154381 0.43549098 0.96244496]]

 [[0.07096103 0.51877994 0.49912656]
  [0.4419501  0.0146701  0.48723217]
  [0.34860123 0.81158099 0.59422935]]

 [[0.79298371 0.25064448 0.19159119]
  [0.59926491 0.05972076 0.79143462]
  [0.37066806 0.28960109 0.9762248 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
a=np.random.rand(10,10)
b=a.min()
c=a.max()
print(a)
print(b)
print(c)

[[0.7354487  0.12556579 0.0537839  0.2948001  0.90527536 0.38993221
  0.44941059 0.52857069 0.19105394 0.03035474]
 [0.1964837  0.08913792 0.80879548 0.14019809 0.78123853 0.93796825
  0.54752502 0.3532146  0.13453718 0.19316947]
 [0.50474408 0.44422569 0.6351113  0.12268026 0.98162757 0.59995508
  0.98218069 0.14925904 0.25479232 0.88736927]
 [0.17391298 0.95653334 0.11601202 0.46088704 0.68886987 0.5265793
  0.81505507 0.01472042 0.58672049 0.36854418]
 [0.20272781 0.26365997 0.14331872 0.63364002 0.85348332 0.27659147
  0.26484962 0.50431741 0.19164357 0.67501099]
 [0.65089713 0.01864455 0.65376321 0.30578026 0.31041841 0.09107204
  0.14442505 0.98465673 0.62648036 0.13458551]
 [0.53748709 0.56005025 0.923292   0.83831349 0.52142333 0.45187918
  0.84554706 0.31075505 0.73596467 0.01837567]
 [0.0051479  0.60566891 0.29669433 0.86244267 0.52037657 0.24014414
  0.4459192  0.10612376 0.84797593 0.18095151]
 [0.94663525 0.24810939 0.93579102 0.2246581  0.37653639 0.49872246
  0.89636931 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
a=np.random.rand(30)
b=a.mean()
print(a)
print(b)

[0.65257425 0.57600712 0.1278606  0.22855387 0.60681622 0.76255581
 0.06899772 0.48962305 0.69493186 0.15385432 0.44500801 0.84679326
 0.19625775 0.37283377 0.02541143 0.41959261 0.02826647 0.89327835
 0.39401574 0.64687303 0.31923828 0.25480882 0.99057506 0.5100645
 0.07602996 0.44893253 0.30030885 0.02090297 0.82487013 0.05626171]
0.4144032683947167


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [30]:
a=np.arange(9)
b=a.reshape(3,3)
print(b)
border=np.zeros((5,5))
border[1:-1,1:-1]=b
print(border)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
a=np.arange(0,25)
b=a.reshape(5,5)
np.fill_diagonal(b,[1,2,3,4])
print(b)

[[ 1  1  2  3  4]
 [ 5  2  7  8  9]
 [10 11  3 13 14]
 [15 16 17  4 19]
 [20 21 22 23  1]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [36]:
shape=(6,7,8)
ind=np.unravel_index(99,shape)
print(ind)


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [40]:
a=np.array([[0,1],
          [1,0]])
b=np.tile(a,(4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [41]:
a=np.random.rand(5,5)
b=a.min()
c=a.max()
norm=(a-b)/(c-a)
print(norm)

[[2.79130790e-01 5.89859841e-01 0.00000000e+00 8.55638206e+00
  2.84362128e+00]
 [5.37290841e-01            inf 3.42625026e+00 2.37257066e-01
  7.78720622e-03]
 [8.08444716e-02 3.38285734e-01 4.16355240e-01 4.29203487e+00
  1.43778732e+00]
 [4.96569665e-01 4.63440944e-02 3.79568375e+00 1.41045751e-01
  1.39997070e+00]
 [5.64872487e-01 6.35209451e-01 1.84013247e+01 6.11107762e-01
  4.76243718e-01]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_1704\1682006495.py:4: RuntimeWarning: divide by zero encountered in divide
  norm=(a-b)/(c-a)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [44]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
a=np.array((200,1,0,125),dtype=color_dtype)
print(a)

(200, 1, 0, 125)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [45]:
a=np.random.rand(5,3)
b=np.random.rand(3,2)
resu=a@b
print(resu)

[[1.360359   0.6701837 ]
 [0.99465151 0.84996057]
 [0.41489602 0.24816713]
 [0.60990547 0.3265103 ]
 [0.59276781 0.4636371 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [47]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[(a>=3)&(a<=8)]*=-1
print(a)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
float_array = np.array([-2.7, 1.3, 2.5, -3.8, 4.1])
r_a=np.where(float_array>=0,np.ceil(float_array),np.floor(float_array))

print(r_a)

[-3.  2.  3. -4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [1]:
import numpy as np

# Create two NumPy arrays as examples
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

# Print the common values
print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [3]:
A=np.array([1,2,3,4])
B=np.array([1,2,4,5])
A+=B
A*=-0.5
print(A)

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
def integer_generator():
    for i in range(10):
        yield i
        
integers=np.array(list(integer_generator()))   
print(integers)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
a=np.linspace(0,1,10,endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [12]:
a=np.arange(10)
b=np.sort(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)