In [1]:
l = [1,2,'3',True]

import numpy as np

a = np.array([1,2,3.4])

array([1, 2, 3])

In [2]:
type(l)

list

In [18]:
a = np.array([1,2,3])

In [4]:
a

array([1. , 2. , 3.4])

In [9]:
a.ndim

1

In [12]:
b = np.array([[1,2,3],
             [4,5,7]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [8]:
b.ndim

2

In [16]:
l + [4]

[1, 2, 3, 4]

In [22]:
a = a * 2

array([2, 4, 6])

In [23]:
a

array([1, 2, 3])

In [25]:
l.append(4)

In [26]:
l

[1, 2, 3, 4]

In [32]:
b[0][:2]

array([1, 2])

In [35]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full((4,4),-6, dtype=int)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

In [41]:
np.arange(1,11,2.5)

array([1. , 3.5, 6. , 8.5])

In [48]:
a = np.arange(1,11)

In [47]:
a[3:6]*= -1
print(a)

[ 1  2  3 -4 -5 -6  7  8  9 10]


In [54]:
a[(a>3) & (a<7)] *= -1

In [55]:
a

array([ 1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [61]:
b = a.reshape((2,5))

In [62]:
b

array([[ 1,  2,  3, -4, -5],
       [-6,  7,  8,  9, 10]])

In [63]:
b.flatten()

array([ 1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [64]:
np.mean(a)

2.5

In [65]:
np.std(a)

5.678908345800274

In [66]:
b

array([[ 1,  2,  3, -4, -5],
       [-6,  7,  8,  9, 10]])

In [69]:
np.mean(b, axis=0)

array([-2.5,  4.5,  5.5,  2.5,  2.5])

In [ ]:
np.median()